### ISSUE TITLE
buying cars and recieve key and npc crash

### ISSUE THREAD

**Issue by ZypsohSaturn** [Mono-94/sy_carkeys#1]
when i buy a car i dont recieve the key i used TriggerEvent('sy_carkeys:KeyOnBuy', props.plate, props.model) and when we open the locksmith we get a crash
![image](https://user-images.githubusercontent.com/117955622/224880143-282fe1b6-df34-49af-8e09-4c5edeba8695.png)

**Comment by Mono-94** [comment]
could print props.plate, props.model
to see what result it gives

**Comment by ZypsohSaturn** [comment]
i get "ESX3N604	-285576169" when printing props.plate, props.model which i would think theyre correct

**Comment by Mono-94** [comment]
Can you show me the code where you are using it?

**Comment by ZypsohSaturn** [comment]
and the crash nothing logs client or server wise

**Comment by ZypsohSaturn** [comment]
> Can you show me the code where you are using it?

RegisterNetEvent('s4-vehicleshop:server:givecar')
AddEventHandler('s4-vehicleshop:server:givecar', function(props)
    local src = source
    local Player = ESX.GetPlayerFromId(src)
    exports.ghmattimysql:execute("INSERT INTO owned_vehicles (owner, plate, vehicle) VALUES ('"..Player.identifier.."', '"..props.plate.."', '"..json.encode(props).."')", {  })
    TriggerEvent('sy_carkeys:KeyOnBuy', props.plate, props.model)
    --Player.addInventoryItem('carkey', 1, false, info)
    --print(Player.source..' ARAC SATIN ALDI')
end)

this is the handler that i am using to give the key

**Comment by ZypsohSaturn** [comment]
do you want the whole thing?

**Comment by Mono-94** [comment]
RegisterNetEvent('s4-vehicleshop:server:givecar')
AddEventHandler('s4-vehicleshop:server:givecar', function(props)
    local src = source
    local Player = ESX.GetPlayerFromId(src)
    exports.ghmattimysql:execute(
    "INSERT INTO owned_vehicles (owner, plate, vehicle) VALUES ('" ..
    Player.identifier .. "', '" .. props.plate .. "', '" .. json.encode(props) .. "')", {})
    --TriggerEvent('sy_carkeys:KeyOnBuy', props.plate, props.model)
    print('Plate = '.. props.plate..' Model = '..props.model)
    --Player.addInventoryItem('carkey', 1, false, info)
    --print(Player.source..' ARAC SATIN ALDI')
end)
print this

**Comment by ZypsohSaturn** [comment]
here is the result: Plate = ESX4H241 Model = -1189478547

**Comment by Mono-94** [comment]
the model is obenindoun hash with the model and has to get the name of the model, for example karin brand, sultan model.
I recommend that you use the event on the client side for easier access to the model.

**Comment by ZypsohSaturn** [comment]
yep i made it client sided and its working perfectly now thanks

**Comment by ZypsohSaturn** [comment]
only problem now is that the npc is still crashing xd

**Comment by Mono-94** [comment]
in what sense does it keep failing?

**Comment by Mono-94** [comment]
How strange, do you use the latest version of oxmysql?

**Comment by ZypsohSaturn** [comment]
Yep

**Comment by Mono-94** [comment]
I'm not having that problem.

**Comment by ZypsohSaturn** [comment]
maybe its a problem with my fivem idk i will call a friend tommorow and he tests

**Comment by Mono-94** [comment]
Clear fivem cache, maybe it will be solved. I hope I have helped!
